### Get All Contacts
GET http://localhost:3000/contacts

### Get Single Contact
GET http://localhost:3000/contacts/6a09008857de57d4e6adab0b

### Create Contact
POST http://localhost:3000/contacts
Content-Type: application/json

{
  "firstName": "James",
  "lastName": "Brown",
  "email": "james@example.com",
  "favoriteColor": "Black",
  "birthday": "1999-08-20"
}

### Update Contact
PUT http://localhost:3000/contacts/6a133ead1a16c7f67c76dc3f
Content-Type: application/json

{
  "firstName": "Maryanne Updated",
  "lastName": "Smith",
  "email": "maryanneupdated@gmail.com",
  "favoriteColor": "Blue",
  "birthday": "2000-02-14"
}

### Delete Contact
DELETE http://localhost:3000/contacts/6a133f331a16c7f67c76dc40